### ISSUE TITLE
How do you yield* with async/await?

### ISSUE THREAD

**Issue by Fishrock123** [tc39/proposal-async-await#100]
Hi there, I was looking to move my CLI tool [org-labels](https://github.com/repo-utils/org-labels) over to async/await as an experiment, using [node+v8-5.2](https://github.com/nodejs/CTC/issues/7#issuecomment-229901469) & `--harmony_async_await`.

I've noticed there does not immediately appear to be a replacement for `yield*`, as with the `co` library.

That is, it is unclear what you need to do to wait for all `await`s to resolve within an `async` function...

**Comment by kittens** [comment]
```javascript
await Promise.all(arrayOfPromises);
```

**Comment by Fishrock123** [comment]
@kittens Given the following: _(They deleted their comment...)_

``` js
async function a() {
  await x; // must wait for this
  await y; // AND this
}

async function b() {
  await a(); // previously `yield* a()`
}
```

do you mean `await Promise.all(a())`? Will the async function with multiple awaits return an array?

Always or only when multiple exist/are run?

**Comment by ilkkao** [comment]
Similar issue: https://github.com/tc39/ecmascript-asyncawait/issues/61

**Comment by raymond-h** [comment]
Async functions with multiple awaits still only return a single promise, which is resolved once the function has finished. `await` makes it wait for a given promise to resolve before the function is continued.

With multiple `await`s, it'll wait until the first promise is resolved, then the second promise, then the third promise, etc, until the end of the function has been reached. At that point, the promise that the function as a whole returned is resolved.

In your example, when `b` is called, it'll call `a` and get a promise that it waits for to get resolved. The function `a`, in turn, waits for promise `x` to be resolved, then promise `y`. Once that's done, `a` returns, at which point the promise that was gotten by `b` is resolved.

**Comment by raymond-h** [comment]
Because an async function that awaits on promises itself returns a promise that is resolved when the async function return, `await` works for awaiting the result of other async functions too out of the box, so it is a non-issue essentially.

**Comment by Fishrock123** [comment]
Hmm, ok. Looks/sounds like this is the default behavior. In a bit of hindsight that makes sense.

That being said I _am_ running into problems related to this, but not really this issue.
