### ISSUE TITLE
Proposal: parallelize consecutive awaits

### ISSUE THREAD

**Issue by wheresrhys** [tc39/proposal-async-await#106]
I'm mostly quite excited by the new await/async syntax, but have one reservation. Naively, the following two bits of code look equivalent, but the first is actually far more performant as the two async operations run in parallel.

``` js
function () {
const a = asyncOne();
const b = asyncTwo();
return Promise.all([a, b])
}
```

``` js
async function () {
const a = await asyncOne();
const b = await asyncTwo();
return [a, b];
}
```

Would it be feasible to have _strictly_ consecutive awaits running in parallel. By strictly consecutive I mean that latter ones must not depend on the results of the former ones, and no other statements must be executed in between them. 

The benefits are it's easier to do the most performant thing, and potentially easier to convert existing Promise based code to async. On the negative side, I'm not sure how easy it is for the js engine to determine whether later awaits are independent of the results of former ones. Arguably it also adds unpredictability to the API (though, on first glance, I don't _think_ this would break any await/async code that uses the current behaviour)

**Comment by ljharb** [comment]
How would you suggest the engine be statically able to know that `asyncOne` does not depend on anything in `asyncTwo`? Here, `await` is statically indicating that it does depend on it.

**Comment by wheresrhys** [comment]
After giving it more thought I realised that this change could break existing code (as asyncTwo could expect some external value to be changed by asyncOne)... so for that reason I doubt this is worth considering for such a late stage proposal. Also, you're right that the static analysis is tricky as asyncOne could dynamically choose external values to change at runtime.

Perhaps there would be scope for an additional keyword which means 'await in parallel', and which allows the developer to specify which Promises can be awaited in parallel. Which would be little more than syntactic sugar around `await Promise.all()`, but would contribute to the sync/async symmetry that async/await aims towards.

**Comment by ljharb** [comment]
Note that this isn't just "late stage", this is finished - ie, stage 4.

Syntactic sugar for `await Promise.all(…)` existed very early in this proposal, but was largely rejected, as I understand it (`await*`)

**Comment by qfox** [comment]
> Syntactic sugar for await Promise.all(…) existed very early in this proposal, but was largely rejected, as I understand it (await*)

Yep, exactly.
