### ISSUE TITLE
Error in javascript discord bot

### ISSUE THREAD

**Issue by Deducts** [tc39/proposal-async-await#113]
> > import { prefix as _prefix, token } from "./botconfig.json";
> > import { Client } from "discord.js";
> 
> > const bot = new Client({disableEveryone: true});
> 
> > bot.on("ready", async () => {
>   > console.log('Discord bot is online!');
>   > bot.user.setActivity("on DeductsDick")
> > });
> 
> > bot.on("message", async message => {
>   > if(message.author.bot) return;
>  >  if(message.channel.type === "dm") return;
> 
>   > let prefix = _prefix;
>   > let messageArray = message.contact.split("  ");
>   > let cmd = messageArray[0];
>   > let args = messageArray.slice(1);
> 
>   > if(message.content === '${prefix}hello'){
>     > return message.channel.send("Hello!");
>   > }
> 
> > });
> 
> > bot.login(token);

That is my current code. I type > node index.js

and it runs fine. But as soon as i type a command in my discord server it comes up with this error code:

> (node:56152) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'split' of undefined    at Client.bot.on (C:\Users\skyhe\Documents\test\index.js:16:38)
>     at Client.emit (events.js:182:13)
>     at MessageCreateHandler.handle (C:\Users\skyhe\Documents\test\node_modules\discord.js\src\client\websocket\packets\handlers\MessageCreate.js:9:34)
>     at WebSocketPacketManager.handle (C:\Users\skyhe\Documents\test\node_modules\discord.js\src\client\websocket\packets\WebSocketPacketManager.js:103:65)
>     at WebSocketConnection.onPacket (C:\Users\skyhe\Documents\test\node_modules\discord.js\src\client\websocket\WebSocketConnection.js:333:35)
>     at WebSocketConnection.onMessage (C:\Users\skyhe\Documents\test\node_modules\discord.js\src\client\websocket\WebSocketConnection.js:296:17)
>     at WebSocket.onMessage (C:\Users\skyhe\Documents\test\node_modules\ws\lib\event-target.js:120:16)
>     at WebSocket.emit (events.js:182:13)
>     at Receiver._receiver.onmessage (C:\Users\skyhe\Documents\test\node_modules\ws\lib\websocket.js:137:47)
>     at Receiver.dataMessage (C:\Users\skyhe\Documents\test\node_modules\ws\lib\receiver.js:409:14)
> (node:56152) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
> (node:56152) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

Any assistance in what i can add to my code to make this work like normal?

**Comment by ljharb** [comment]
@Deducts it sounds like you have a general question about some JS code - but this repo is the proposal for a now-standard language feature.

Specifically, on line 16 of `test/index.js`, you're calling `.split()` on something that's `undefined` and not a string.
