### ISSUE TITLE
> > Btw, what's the case of exporting async function atm? Can't imagine a single one, even if it's a valid syntax.

### ISSUE THREAD

**Issue by SummerXIAhaha** [tc39/proposal-async-await#118]
> > Btw, what's the case of exporting async function atm? Can't imagine a single one, even if it's a valid syntax.
> 
> E.g.:
> 
> _fetch.js_
> 
> ```js
> export default async function(url) {
>    var data = await request(url);
> 
>    return JSON.parse(data);
> }
> ```
> 
> _index.js_
> 
> ```js
> import fetch from './fetch';
> 
> fetch('http://example.com').then(data => {
>    ...
> });
> ```

if I need export the data in index.js. how can i get it? 

_Originally posted by @SummerXIAhaha in https://github.com/tc39/ecmascript-asyncawait/issues/74#issuecomment-497925365_

**Comment by ljharb** [comment]
You can’t get the data outside a promise - so you export the promise, and you get it inside the .then (or you await the promise)

**Comment by SummerXIAhaha** [comment]
> You can’t get the data outside a promise - so you export the promise, and you get it inside the .then (or you await the promise)

ok, I know it, thank you~
