### ISSUE TITLE
node google spreadsheet i want to fetch a particular cell

### ISSUE THREAD

**Issue by jatinkumarrao** [tc39/proposal-async-await#119]
const creds =require ('./data.json');

   console.log('Questions: ${student.Activities & Employment}');
   console.log('sub 1 tab: ${student.sub 1 tab}');
 
async function accessSpreadsheet(){
  const doc = new GoogleSpreadsheet('spreadsheet-ID');
  await promisify(doc.useServiceAccountAuth)(creds);
  const info = await promisify(doc.getInfo)();
  const sheet = info.worksheets[0];
  console.log('Title: ${sheet.title}, Rows: ${sheet.rowCount}')
    const rows =await promisify(sheet.getRows)({
      query: 'sub 1 tab = Q1'
});
    rows.forEach(row=>{
       printStudent(row);
    })
  }
accessSpreadsheet();
})

**Comment by ljharb** [comment]
This is unrelated to this proposal.
