### ISSUE TITLE
Question: Async/await vs decorators

### ISSUE THREAD

**Issue by ashmind** [tc39/proposal-async-await#14]
I wonder if the proposal might be defined in a more generic way using some kind of a decorator function syntax.

E.g.

``` javascript
@async function* chainAnimationsAsync(elem, animations) {
    var ret = null;
    try {
        for(var anim of animations) {
            ret = yield anim(elem);
        }
    } catch(e) { /* ignore and keep going */ }
    return ret;
}
```

where `@async` is decorator function (basically `spawn` function from non-async example).

**Comment by lukehoban** [comment]
While it would be nice to have richer decorator support as well, I think this proposal still stands on it's own.
