### ISSUE TITLE
Need cover grammar for async arrow funciton

### ISSUE THREAD

**Issue by arv** [tc39/proposal-async-await#18]
We need cover grammar since `async(x, y)` can either be a CallExpression or the beginning of a AsyncArrowFunction.

**Comment by bterlson** [comment]
I think I've fixed this in the latest. @arv, please review if you can: http://tc39.github.io/ecmascript-asyncawait/ (see _CoverCallExpressionAndAsyncArrowHead_).

Need to update many static semantics for CallExpression to handle the presence of the cover grammar but will do that later...

**Comment by arv** [comment]
There are some CoveredCallExpressionAndAsyncArrowHead instead of CoverCallExpressionAndAsyncArrowHead in there

**Comment by arv** [comment]
LGTM minus the typo. Thanks.

**Comment by bterlson** [comment]
Fixed the typos. Thanks Arv!!
