### ISSUE TITLE
Loosen no LineTerminator here

### ISSUE THREAD

**Issue by arv** [tc39/proposal-async-await#19]
``` js
async x => x
```

If the `ArrowParameters` is a single `BindingIdentifier` there is no need for the `[no LineTerminator here]` after the `BindingIdentifier`.

**Comment by bterlson** [comment]
Done so, but not sure if I've done so correctly (there are no other cases where a [no LineTerminator here] appears at the end of an alternative but I think it should be fine.

Unfortunately doing this will require duplicating additional static semantics from ArrowParameters... will do that soon.
