### ISSUE TITLE
wishlist: some way of adding async/await to TypeScript (preprocessor, fork of compiler, sweet.js-like thing, whatever)

### ISSUE THREAD

**Issue by jamesmanning** [tc39/proposal-async-await#21]
I know it's on the TypeScript team's roadmap, but it's so painful that you can get async/await and all of ES6 with traceur --experimental, but there's no way (AFAICT) to leverage that while still using TypeScript.

Most of the ES6 features I can wait for TypeScript to add, but async/await is both the biggest draw (IMHO) and the one that appears the furthest out on their roadmap.

Since it looks like the compiler transform and runtime impl are pretty well known at this point, is there any way to get async/await into TypeScript?  I understand that tooling support will be extremely unlikely, but even if it's only supported by the command-line compiler, that would still be a huge win over having to keep waiting for TypeScript to get it.

Thanks!

**Comment by lukehoban** [comment]
See https://github.com/Microsoft/TypeScript/issues/1664.

**Comment by jamesmanning** [comment]
Thanks, @lukehoban !!
