### ISSUE TITLE
await* and parallelism is not ideal

### ISSUE THREAD

**Issue by davidbau** [tc39/proposal-async-await#25]
The proposed await\* syntax is not ideal for parallelism.  When managing parallel tasks, it is typical to have a set of dissimilar tasks, each launched and finished in a different way.  Instead of reducing boilerplate, an idiom where each result needs to be packed and unpacked into an array would increase ceremony

Can we do something that is closer to what is achieved by Iced CoffeeScript?  There they have a keyword which introduces a block, within which you should not expect to be able to use the result.  Their syntax is something like this:

<pre>
await
  $.get myurl1, defer result1
  douserinput defer result2
  for j in [0...10]
    $.get myurlarray[j], defer resultarray[j]
# within the wait block, all the requests are launched in parallel...
# then the await block ends, which pauses the program, then after that we have results
answer = result1+ result2 + sum(resultarray)
</pre>

The main advantage here is clarity: the variable name for the result is directly next to the operation that computes it.

Rather than an array-based await\* I think it would be much better to try to mimic Iced's simplicity:

<pre>
await* {
  result1 = await urlget(url1)
  result2 = await douserinput()
  for (var j = 0; j &lt; 10; ++j) {
    resultarray[j] = await urlget(urlarray[j])
  }
}
</pre>

Would something like that be possible?

**Comment by matAtWork** [comment]
I have a similar issue over in https://github.com/lukehoban/ecmascript-asyncawait/issues/29 - whether and how it is desirable to provide a language construct to specify parallelism. My proposal is to be able to precede a loop with the `async` keyword.

**Comment by MatAtBread** [comment]
In nodent, the library function akin to Promise.all (nodent.map) accepts an object as it's argument, as well as an array, giving results like:

```
var r = await nodent.map({
  URL:getUrl("home"),
  input:doUserInput(elem)
}) ;

redirect(r.URL+"?"+r.input);

```

This has the advantage of keeping the operation and name in close proximity, making the intent easier to spot, is fully ES5 friendly with respect to the await expression and response, allows for nested parallel persons, and in any case is a runtime implementation and so the programmer can alias the function. I'm not sure there is any real value in creating new syntax to cover this case.

The source at https://github.com/MatAtBread/nodent/blob/master/covers/map.js also allows for an array, object to counter to be mapped by an asynchronous function as a second parameter, but this is simply for convenience and not directly related to the use case in question here

**Comment by davidbau** [comment]
That's nice, and that would solve the problem that concerns me.
Promise.all doesn't work that way?

**Comment by lukehoban** [comment]
I think it is worth suggesting that change to `Promise.all` behavior to TC39 as part of the Promise API.  It would be a nice addition that would help here.

I don't think there is anything that needs to change in the async/await proposal related to this thread at this point.

**Comment by MatAtBread** [comment]
If someone has a mechanism for submitting this to the correct TC39 group, please feel free to do so (I don't)

**Comment by getify** [comment]
@MatAtBread you can join the https://mail.mozilla.org/listinfo/es-discuss discussion list, which is how non-TC39'rs submit suggestions/discussions for TC39 to consider.
