### ISSUE TITLE
await does not chain well - alternate syntax needed

### ISSUE THREAD

**Issue by bjouhier** [tc39/proposal-async-await#26]
await does not chain well. Consider:

```
result = await (await (await f1()).f2()).f3();
```

I've been using an async/await substitute (steamline.js) for several years and we have a lot of code that chains async calls. With streamline we write the above as:

```
result = f1(_).f2(_).f3(_);
```

The streamline.js syntax is a hack (for practical reasons it was easier to reserve a token than to extend the grammar) but why not use the sugar proposed in the concurrency strawman?(http://wiki.ecmascript.org/doku.php?id=strawman:concurrency):

```
result = f1!().f2!().f3!();
```

**Comment by lukehoban** [comment]
Closing this issue out for now.  

The design point that `async/await` as a proposal takes is very much the one @zenparsing has spoken to here.

Importantly, with `await` you can (and very often do) also await a value, not just the result of a function call.  This necessitates syntax that fits cleanly into the expression grammar. 

If I consider real world async code, I don't think it's clear that the syntax suggestion here is a net win.
