### ISSUE TITLE
grammar needs to disallow async in ExpressionStatement lookahead

### ISSUE THREAD

**Issue by michaelficarra** [tc39/proposal-async-await#28]
Because `async` is allowed as the first token of both a statement (`AsyncFunctionDeclaration`) and an expression (`AsyncFunctionExpression`), the grammar for `ExpressionStatement` needs to be updated to disallow `async` in its lookahead. See section [13.4](https://people.mozilla.org/~jorendorff/es6-draft.html#sec-expression-statement) for more info.

**Comment by bterlson** [comment]
Don't we need to disallow "async function" rather than async? The latter would disallow async arrow functions as expression statements which, while potentially useless, doesn't mesh with the arrow function grammar...

Can we look ahead two tokens? I guess the "let [" one does already...

**Comment by michaelficarra** [comment]
:+1: "async function" is the appropriate lookahead restriction
