### ISSUE TITLE
Question: OK to return Promises from async functions?

### ISSUE THREAD

**Issue by ide** [tc39/proposal-async-await#30]
Reading the proposed implementation it looks like this should work because async functions support promise chaining in their return values:

``` javascript
async function exampleAsync() {
  return helperAsync();
}
async function helperAsync() { ... }
```

Specifically note that there is no `await` keyword in front of the call to `helperAsync()`. This actually seems good because it avoids an extra traversal up and down the stack compared to `return yield helperAsync()`. Just want to make sure this is intentional.

**Comment by arv** [comment]
That should work because you cannot have a Promises of a Promise. Promises gets unwrapped automatically.

**Comment by ide** [comment]
That's great. Thank you for the clarification.
