### ISSUE TITLE
Scheduling of an async function

### ISSUE THREAD

**Issue by mnieper** [tc39/proposal-async-await#31]
Given the following piece of code:

``` javascript
var list = [];

async function f() {
  list.push(1);
}

var promise = f();
list.push(2);
promise.then(() => {
  /* CODE */
});
```

What shall be the value of list at the beginning of `CODE`? Given the implementation of `spawn`, it will be `[1, 2]`. On the other hand, the usage of async functions in https://github.com/jhusain/asyncgenerator seems to indicate that the output shall be `[2, 1]`, which in fact may make more sense.

**Comment by arv** [comment]
Should be `[1, 2]`. Async functions, unlike generators, does not stall at the entry point.
