### ISSUE TITLE
Sorting arrays with async functions

### ISSUE THREAD

**Issue by iamolivinius** [tc39/proposal-async-await#34]
I'm wondering if it is possible to use an async function to sort arrays. I played a bit around in the babeljs REPL: [see here](http://babeljs.io/repl/#?experimental=true&playground=true&evaluate=true&loose=false&spec=false&code=%20%28async%20function%20%28%29%20%7B%0A%20%20function%20task%28val%29%20%7B%0A%20%20%20%20function%20pReturn%28a%29%20%7B%0A%20%20%20%20%20%20return%20new%20Promise%28%28resolve%2C%20reject%29%20%3D%3E%20%7B%0A%20%20%20%20%20%20%20%20setTimeout%28%28%29%20%3D%3E%20%7B%0A%20%20%20%20%20%20%20%20%20%20resolve%28a%29%3B%0A%20%20%20%20%20%20%20%20%7D%2C%20500%29%3B%0A%20%20%20%20%20%20%7D%29%0A%20%20%20%20%7D%0A%20%20%0A%20%20%20%20async%20function%20getMe%28%29%20%7B%0A%20%20%20%20%20%20return%20%28await%20pReturn%28val%29%29%3B%0A%20%20%20%20%7D%0A%20%20%0A%20%20%20%20return%20Object.freeze%28%7B%0A%20%20%20%20%20%20val%2C%0A%20%20%20%20%20%20getMe%0A%20%20%20%20%7D%29%3B%0A%7D%0A%0Alet%20tasks%20%3D%20%5Btask%2822%29%2C%20task%2810%29%2C%20task%2815%29%5D%3B%0A%0Aconsole.log%28JSON.stringify%28tasks%29%29%3B%0A%0Atasks.sort%28async%20function%20%28t1%2C%20t2%29%20%7B%0A%20%20return%20%28await%20t1.getMe%28%29%29%20-%20%28await%20t2.getMe%28%29%29%3B%0A%7D%29%3B%0A%0Aconsole.log%28JSON.stringify%28tasks%29%29%0A%20%20%0A%7D%28%29%29%0A%0A)

``` es6
(async function() {
  function task(val) {
    function pReturn(a) {
      return new Promise((resolve, reject) => {
        setTimeout(() => {
          resolve(a);
        }, 500);
      });
    }

    async function getMe() {
      return (await pReturn(val));
    }

    return Object.freeze({
      val,
      getMe
    });
  }

  let tasks = [task(22), task(10), task(15)];

  console.log(JSON.stringify(tasks));

  tasks.sort(async function(t1, t2) {
    return (await t1.getMe()) - (await t2.getMe());
  });

  console.log(JSON.stringify(tasks))
}())
```

Is it not supposed to work or am I doing it wrong?

**Comment by zenparsing** [comment]
Async functions return a promise, so the sort callback in your example is returning promises, not numeric values.  Does that make sense?  You would need to await the result of each task before sorting, or create your own async sort function.

**Comment by iamolivinius** [comment]
Makes sense :) But how do you await the result of each task? Like this?

``` es6
tasks.sort(await (async function(t1, t2) {
    return (await t1.getMe()) - (await t2.getMe());
}));
```

**Comment by lukehoban** [comment]
You can await the results of each task by doing something like this:

``` javascript
let values = await Promise.all(tasks.map(task => task.getMe()))
values.sort(function(t1, t2) {
  return t1 - t2;
});
console.log(JSON.stringify(values))
```

This means that all of the promises must be resolved before sorting can begin.

By creating an asynchronous sort implementation, you could in principle allow some of the sorting to happen concurrently with the promises resolving.  Things like [async-q](https://github.com/dbushong/async-q/blob/master/async.coffee#L101) appear to implement something along these lines for sorting over promises.
