### ISSUE TITLE
What happens when an exception is thrown from a parameter initializer?

### ISSUE THREAD

**Issue by zenparsing** [tc39/proposal-async-await#35]
If an exception is thrown during evaluation of a parameter default initializer, does it result in an exception, or a rejected promise?

``` js
async function f(a = (null).x) {}
f();  // Exception or rejection?
```

**Comment by domenic** [comment]
Rejected promise, please!

**Comment by lukehoban** [comment]
The current rewrite in the spec text would produce an exception.

I understand the desire to have it be a rejected promise instead for consistency with the rest of the "body" evaluating inside the promise.

What do generators in ES6 do?  I think it would be awkward to be inconsistent.  Babel at least currently throws "early" on this example, which is unexpected for the same reason (I haven't called `next` to pull on the execution of the function body yet).

``` javascript
function* f(a = (null).x) {}
var x = f(); // Error: Cannot read property 'x' of null
```

Of course, honestly, if you write parameter default value expressions which can ever throw, you are shooting yourself in the foot to begin with, so to some extent I'm not sure this is a big deal either way.

**Comment by zenparsing** [comment]
@lukehoban when generator functions are called, the parameters are bound (and defaults are evaluated) before the execution context is suspended.  It's sort of like the generator is suspended at the body's opening brace.  I'm not sure it really bears too much on this question, though.

I think it should probably return a rejected promise for the following reason:  If I call an async function, I expect to respond to the resulting control flow (whether exception or return) asynchronously.  I'm not going to want to deal with a mixture of async and sync control flow arising out of that call.

**Comment by lukehoban** [comment]
@zenparsing Totally agree on the reason for wanting this to return a rejected promise.  I'd argue there's a similar reason to want generators to do the equivalent:

``` JavaScript
function* f(a = (null).x) {}
var x = f(); // do I get an exception here?
x.next(); // or here?
```

Any exception thrown within the body of the generator won't throw till the call to `next`, so for the most part I never have to worry about exceptions thrown out of the invocation of the generator function.  Except that apparently parameter default expressions are evaluated in a context that can throw out of the generator function invocation.

Of course, this is somewhat more painful to workaround for async/await.

Unfortunately, I don't think there is any way to spec/implement async/await with this semantics on top of generators assuming they intentionally have a different semantics.

I was really hoping that async/await would not have to invent any new semantics - it would just be pure sugar over generators + Promises.

**Comment by bterlson** [comment]
At the July TC39, the committee got consensus on going the route of default parameter errors being handled by the promise rather than thrown directly from the function.

**Comment by bterlson** [comment]
Closing this now as it is tracked in #60.
