### ISSUE TITLE
Top level awaits

### ISSUE THREAD

**Issue by ivan-kleshnin** [tc39/proposal-async-await#36]
Is there any notion or plans for such thing? In Node we use `doSomeStuffSync` in global (module) space, where concurrency isn't required and order of commands really matters. 

``` javascript
// this is global space
let x = a.doStuffSync();
let y = b.doOtherStuffSync(x);  
```

But global-space `await`s could obsolete those `Sync` -suffixed functions and open the possibility to remove them entirely.

``` javascript
// this is global space, no "async" function wrapper
let x = await a.doStuff(); 
let y = await a.doOtherStuff(x); 
```

Of course, if `a.doOtherStuff` accepts promises it may be implemented on usual async versions, but if it's not (most of today's API), we'll have an option. I'm not sure about technical possibility for this, just asking. But this have special benefits like 

``` javascript
let x = await a.doStuff(); 
console.log(x);
// vs
let x = a.doStuff().then(function(v) { console.log(v); return v; }); 
```

**Comment by domenic** [comment]
We specifically reserved `await` at top-level in modules to account for this possibility. Nobody's had the time to really figure out the semantics yet, though.

**Comment by ivan-kleshnin** [comment]
Oh, cool, thank's for the response.

**Comment by zenparsing** [comment]
We're probably not ready for this yet, but for the record there are two solutions that make sense to me:

For server-side systems, it makes sense to me to have a `main` function which defines program entry.  If the executed module exports a `main` function, then it would run that.  The `main` function could be an async function.

Also, if we ever get do-expressions, then it would makes sense to also have a do-async-expression.

``` js
do async {
  let x = await a.doStuff(); 
  let y = await a.doOtherStuff(x);
}
```

My personal opinion is that we should not allow modules themselves to be async, for simplicity and separation of concerns.  Also, I don't think we want to outright reject the possibility of a system which loads modules synchronously and doesn't need to worry about async within the module system itself.

**Comment by lukehoban** [comment]
Note that there is also quite a bit of discussion on this same topic in https://github.com/lukehoban/ecmascript-asyncawait/issues/9.  

I'll close this issue to keep a single thread of discussion on top level await.
