### ISSUE TITLE
Bind generator to callers 'this' to enable async methods

### ISSUE THREAD

**Issue by MatAtBread** [tc39/proposal-async-await#37]
Unless I've missed something, the construct:

```
    function aClass() { this.value = 0; } 
    function aClass.prototype.inc = async function() { 
        this.value += 1 ;
        return this.value ;
    }

    var x = new aClass() ;
    var y = x.inc() ;
```

...fails because within the async function 'this' is not bound to x. In my own implementation, this is fixed by modifying the 'spawn' function so that

```
function spawn(genF) {
    return new Promise(function(resolve, reject) {
        var gen = genF();
        ....
```

is replaced by 

```
function spawn(genF,self) {
    return new Promise(function(resolve, reject) {
        var gen = genF.call(self);
        ....
```

...and the invokation rewrite from

```
  async function <name>?<argumentlist><body>
  =>
  function <name>?<argumentlist>{ return spawn(function*() <body>); }
```

to

```
  async function <name>?<argumentlist><body>
  =>
  function <name>?<argumentlist>{ return spawn(function*() <body>,this); }
```

**Comment by arv** [comment]
The spawn function is only informative. A spec for this would explain the semantics differently.

Both traceur and babel does the right thing:

http://google.github.io/traceur-compiler/demo/repl.html#%2F%2F%20Options%3A%20--async-functions%0A%0Afunction%20aClass()%20%7B%20this.value%20%3D%200%3B%20%7D%20%0AaClass.prototype.inc%20%3D%20async%20function()%20%7B%20%0A%20%20this.value%20%2B%3D%201%20%3B%0A%20%20return%20this.value%20%3B%0A%7D%0A%0Avar%20x%20%3D%20new%20aClass()%20%3B%0Avar%20y%20%3D%20x.inc()%3B%0Ay.then((v)%20%3D%3E%20%7B%0A%20%20console.log(v%2C%20x%2C%20y)%0A%7D)%3B%0A

https://babeljs.io/repl/#?experimental=true&evaluate=true&loose=false&spec=false&playground=false&code=%2F%2F%20Options%3A%20--async-functions%0A%0Afunction%20aClass()%20%7B%20this.value%20%3D%200%3B%20%7D%20%0AaClass.prototype.inc%20%3D%20async%20function()%20%7B%20%0A%20%20this.value%20%2B%3D%201%20%3B%0A%20%20return%20this.value%20%3B%0A%7D%0A%0Avar%20x%20%3D%20new%20aClass()%20%3B%0Avar%20y%20%3D%20x.inc()%3B%0Ay.then((v)%20%3D%3E%20%7B%0A%20%20console.log(v%2C%20x%2C%20y)%0A%7D)%3B%0A

**Comment by MatAtBread** [comment]
Not sure how this fixes the problem - in both cases what is setting "this" inside the function body? It's the asyncSpawn which invokes it, no? 

This issue was attempting to solve the problem (quite possibly a second time) in the spawn() as presented here.
