### ISSUE TITLE
Returning a non-awaited Promise from an async function

### ISSUE THREAD

**Issue by calebboyd** [tc39/proposal-async-await#41]
I'm not sure if this issue has been addressed but could possibly be an area of confusion.
In the analogous C# Task its possible to decouple the parent 'Task' from the child 'Task'
An example can be seen [here (msdn)](https://msdn.microsoft.com/en-us/library/hh228608%28v=vs.110%29.aspx). It would seem as it is defined currently, the following would not be possible with async functions:

<pre><code>async function doSomethingAsync () : Promise&lt;string&gt { ... }</code></pre>

Though the [behavior](http://babeljs.io/repl/#?experimental=true&evaluate=true&loose=false&spec=false&code=let%20somethingAsync%20%3D%20%28%29%20%3D%3E%20new%20Promise%28res%20%3D%3E%20setTimeout%28res%2C%202000%29%29%3B%0Alet%20somethingElseAsync%20%3D%20%28%29%20%3D%3E%20new%20Promise%28res%20%3D%3E%20setTimeout%28%28%29%20%3D%3E%20res%28'value'%29%2C%201000%29%29%3B%0A%0Aasync%20function%20example%20%28%29%20%7B%20%0A%20%20await%20somethingAsync%28%29%3B%0A%20%20console.log%28%60elapsed%3A%20%20%24%7BDate.now%28%29%20-%20start%7D%20ms%60%29%3B%0A%20%20return%20somethingElseAsync%28%29%3B%0A%7D%0Alet%20start%20%3D%20Date.now%28%29%3B%0Aexample%28%29.then%28x%20%3D%3E%20console.log%28%60total%3A%20%20%20%20%24%7BDate.now%28%29%20-%20start%7D%20ms%20%3D%3E%20%24%7Bx%7D%60%29%29%3B) is to be expected when returning a promise from within a promise. There may be cases where that may not be desired.

-- This behavior may only be relevant to future promise specification.

**Comment by bterlson** [comment]
I believe this is a question about promise machinery rather than async functions. It is impossible currently for a promise to resolve to a promise (eg. for the promise returned by the async function call to resolve to the promise returned from the async function body). One workaround for promises and async functions is rather than returning the promise, you box it in an object record. So instead of above you have something like:

```
async function doSomethingAsync () : { promise: Promise<string> } { ... }
```

**Comment by calebboyd** [comment]
Sounds right, I began to think as much after I had raised it. Thanks.
