### ISSUE TITLE
Cover Grammar

### ISSUE THREAD

**Issue by zenparsing** [tc39/proposal-async-await#43]
It looks like currently there's no way for the `async ident =>` form to be parsed by _AsyncArrowFunction_, since _CoverCallExpressionAndAsyncArrowHead_ requires the parens in the argument list.

Also, I see that we have a no-newline restriction at the end of a production, which feels a little strange.  I think I've changed my mind about removing the no-newline restriction before the `=>` in the _BindingIdentifier_ case on the grounds of consistency.  If we add that restriction back in, I _think_ this might be what we're after?

```
AsyncArrowFunction[In, Yield, Await]:
    AsyncArrowHead [no LineTerminator here] => ConciseBody[?In, Await]

AsyncArrowHead[Yield, Await]:
    async [no LineTerminator here] BindingIdentifier[?Yield, Await]
    CoverCallExpressionAndAsyncArrowFormalParameterHead[?Yield, ?Await]

CoverCallExpressionAndAsyncArrowFormalParameterHead[Yield, Await]:
    MemberExpression[?Yield, ?Await] Arguments[?Yield, ?Await]

Supplemental:

AsyncArrowFormalParameterHead[Yield]:
    async [no LineTerminator here] ArrowFormalParameters[?Yield, Await]
```

Could totally be wrong though; cover grammars are a pain.  (Hopefully this will be the last one for a while...)

Maybe @allenwb might want to give this a look?

**Comment by bterlson** [comment]
You are right I think! I missed that the arguments of a call expression are not optional (duh).
