### ISSUE TITLE
A quick status question

### ISSUE THREAD

**Issue by alippai** [tc39/proposal-async-await#45]
Do you plan to move this Proposal to the next stage (Draft) in July (at TC-39)?

**Comment by bterlson** [comment]
Sorry I missed this question!

Yes, I plan to move this forward. I am hoping to have a reviewable draft of the spec text done by then!

**Comment by alippai** [comment]
Awesome!
Just finished transforming and rewriting few tens of thousands LOC. It's more clear, shorter (5-10%) and readable this way - compared to the simple Promise based. Also the webstorm+eslint+babel stack loves the asyncawait.

Thank you, nice work!

**Comment by bterlson** [comment]
Glad to hear you find this feature useful! Is this OSS code? If so I wouldn't mind taking a look at it.

**Comment by alippai** [comment]
No, it's not an OSS - it's a web based client for _Tresorit_ a Dropbox like software, but encrypted on the client-side.
It's going to be open sourced later, but I don't think this happens in 2015. :(

We use a lot of async code not just because of the network, but the Web Workers, Web Crypto, LocalStorage, Message Channel, Web Workers and File APIs. We have long pipelines where we have to run RSA, AES, SHA, PBKDF, GZIP streamed with various concurrency levels and locks to render or download a file.

The simple `Promise.then()` style code got a little bit bloated - it's hard to maintain the variable scope and error handling - so we started to use `Q.async(function*(){ yield ... })`.

Now we switched to `async () => { await ... }` which compiles to the previous `Q` based one.

This syntactic sugar makes no difference from the point of view of debugging, the Promise -> Generator change was harder because we had to split the deployment workflow - now we generate Chrome, Firefox and Edge specific code for development and a regenerator + babel based for Safari/IE11/Firefox ESR. So the Generator -> async/await change was easy, done within a day.

Also using async/await is not only about the easy to read code. We just started to experiment with some static analysis. The async/await code generates simpler AST and we can drop the direct Q dependency from most of the modules as well. The long-term goal is to have a warning/linting system based on type inference and fuzzing (instead of the TypeScript / Flow approach).

There are two features which we solve in a somewhat hacky way:
- cancellation: we use a cancellation token based approach - maybe we should add this with a well written Symbol
- progress propagation: we can stick to the Q.notify() syntax or add some invisible magic pubsub layer or wrapper - maybe we could use Proxies, but there is no Chromium support and no polyfill

**Comment by alippai** [comment]
P.S.: Coming from a traditional educational system (software engineering) where async/await means .NET async/await it was nice to get familiar with Promises and the microtask queue first. It'll be hard to emphasize this is not the same and we shouldn't expect the same behavior. If I'm right, JS has a more [lightweight solution](http://stackoverflow.com/questions/25915634/difference-between-microtask-and-macrotask-within-an-event-loop-context) which has nothing to do with the .NET Tasks.
