### ISSUE TITLE
Parallel awaits

### ISSUE THREAD

**Issue by ajcrites** [tc39/proposal-async-await#46]
Currently it seems like the only way to use `await` with parallel functions is with `Promise.all`, as in https://gist.github.com/ajcrites/e6fd928f1a300bf40cea

It would make sense to me to implicitly convert some structure into a promise awaiting parallel promises to simplify the syntax somewhat.  Parallel operations are common.

My suggestions would be:

```
await [promise1, promise2]
await promise1, promise2
[await promise1, await promise2]
```

I think that the first one makes the most sense -- semantically there should be no reason to call `await` with an array literal.

**Comment by zloirock** [comment]
https://github.com/tc39/ecmascript-asyncawait/issues/8 https://github.com/tc39/ecmascript-asyncawait/issues/25 and [it works in `babel`](https://goo.gl/39Z0rj)

**Comment by ajcrites** [comment]
Thanks for clarifying;
