### ISSUE TITLE
async_generators and for...of

### ISSUE THREAD

**Issue by nikhedonia** [tc39/proposal-async-await#48]
let's take a look at the following snippet:

``` js


function* counter(){
  let i=0;
  while(1){
    yield i++;
  }
}

function wait(time){
  return new Promise(done=>{
    setTimeout(done,time);
  });
}

async function* delay(){
  for(const x of this){
    await wait(1000);
    yield x; 
  }
}

async function logAsyncCount1(){
  var it = counter()::delay();
  console.log('start');
  while(1){
    var obj=await it.next();
    if(obj.done) return;
    console.log(obj.value);
  }
  console.log('end');
}

```

calling `logAsyncCount1` will output a number every second.

Wouldn't it be nice if `logAsyncCount1` could be simplified using `for...of` ?

``` js

async function logAsyncCount2(){
 console.log('start');
  for(var y of /*await*/ counter()::delay() ){
    console.log( /*await*/ y); 
  }
  console.log('end');
}

```

Unfortunaly the proposal does not mention the usage of async-generators in the context of `for...of`
Furthermore, using babel, placing await in both places does not generate the expected output like `logAsyncCount1` does.

i'd love to see this features play nicely together. This would allow us model dataflow in a very pleasing way:

example:

``` js

dataGenerator()
  ::delay(1000)
  ::computeStuff()
  ::tee((computed)=>{
    computed::toStore();
    computed::draw();
})

```

**Comment by nikhedonia** [comment]
gist without strawman operator: https://gist.github.com/nikhedonia/ea8ee9fc503cfcb98479

**Comment by domenic** [comment]
Async generators are a separate proposal. Please see https://github.com/zenparsing/async-iteration/

**Comment by zenparsing** [comment]
@nikhedonia For the async version of for-of specifically, see https://github.com/zenparsing/async-iteration/#the-async-iteration-statement.

It's really cool that regenerator now supports async generators, but "async for-of" will need to be transpiled in babel itself.

**Comment by nikhedonia** [comment]
@zenparsing thanks, cant wait to play around with it!
