### ISSUE TITLE
Carefully scrutinize function kind spec stuff. Do we need a new one?

### ISSUE THREAD

**Issue by domenic** [tc39/proposal-async-await#55]
There are apparently [three notions of function kind in the spec](https://bugs.ecmascript.org/show_bug.cgi?id=4421). FunctionKindA is normal/method/arrow; FunctionKindB is normal/classConstructor/generator; FunctionKindC is normal/non-constructor/generator.
#50 and #54 update the spec to pass "non-constructor" to FunctionAllocate (FunctionKindC), which causes [[FunctionKind]] (FunctionKindB) to be "normal".

In contrast, generators have their own FunctionKindB and FunctionKindC, "generator", which is treated specially throughout the spec. We need to do an audit of all those special treatments and see if async functions need any similar exceptions, and if so, create new FunctionKindB and/or FunctionKindC.

**Comment by domenic** [comment]
OP significantly edited in light of my further investigation in https://bugs.ecmascript.org/show_bug.cgi?id=4421; any emails you may have received are quite outdated.

**Comment by ljharb** [comment]
This proposal is stage 4, and has been merged into the spec as of ES2017.
