### ISSUE TITLE
Allow class methods be async

### ISSUE THREAD

**Issue by premasagar** [tc39/proposal-async-await#58]
I'm expecting something like this would allow class prototype methods to be async, but this is reported as a syntax error.

``` js
export default class {
  constructor () {
  }
  foo () {
  }
  bar async () {
    return await this.foo();
  }
}
```

**Comment by bterlson** [comment]
Try "async bar" rather than "bar async".

**Comment by premasagar** [comment]
Ah, indeed. Thanks. For some reason, having the method name first seemed more intuitive. Probably because it's closer to using `async` in an object:

``` js
{
  foo: async function () {
  }
}
```

Makes sense though.
I hadn't found class methods documented in [lukehoban/ecmascript-asyncawait](https://github.com/lukehoban/ecmascript-asyncawait), at least not explicitly.
