### ISSUE TITLE
Editorial and styling nits

### ISSUE THREAD

**Issue by domenic** [tc39/proposal-async-await#59]
- [x] Since the EMD changes, strings are no longer auto-coded; need to add that back in a few places
- [x] "Defered Functions" is mispelled
- [ ] EMU stylesheet needs styling for emu-const
- [ ] emu-t inside text should not have margin-right. See e.g. https://tc39.github.io/ecmascript-asyncawait/spec-toc.html#async-arrows-static-semantics-Contains step 1
- [x] https://tc39.github.io/ecmascript-asyncawait/spec-toc.html#abstract-ops-async-function-await step 3 is all messed up.
- [ ] Completion(result) is not auto-linking (maybe you meant NormalCompletion?)
- [x] Constructor arguments should not be italicized https://tc39.github.io/ecmascript-asyncawait/spec-toc.html#async-function-constructor-arguments
- [x] Abstract ops need spacing around their parens (or maybe we should get rid of that silly convention)

**Comment by chicoxyzzy** [comment]
What about [`await*`](https://github.com/lukehoban/ecmascript-asyncawait#await-and-parallelism)? It is implemented in Babel.

**Comment by domenic** [comment]
Why do you think that conversation is relevant to this bug?

**Comment by bterlson** [comment]
@chicoxyzzy await* has been removed for some time. You are linking to an extremely old version of this spec :) Please open a new issue if you have one!

**Comment by chicoxyzzy** [comment]
Oops, sorry. Wrong place.
Also there is an [issue](#8) about that already.

**Comment by anba** [comment]
> Completion(result) is not auto-linking (maybe you meant NormalCompletion?)

`Completion(result)` is correct, it is used to highlight that the original completion value `result` is returned as is.

**Comment by bterlson** [comment]
>  https://tc39.github.io/ecmascript-asyncawait/spec-toc.html#abstract-ops-async-function-await step 3 is all messed up.

This was due to the emd greedy comment bug (not present in the actual spec).

> Constructor arguments should not be italicized https://tc39.github.io/ecmascript-asyncawait/spec-toc.html#async-function-constructor-arguments 

I like italicizing all parameters regardless of context (using either _ or | depending on the type of parameter). I'll be using that convention going forward I think :)

**Comment by bterlson** [comment]
Created bterlson/ecmarkup#30 to fix the emu issues you highlighted.

**Comment by domenic** [comment]
> Since the EMD changes, strings are no longer auto-coded; need to add that back in a few places

Still spotting some of these, e.g. https://tc39.github.io/ecmascript-asyncawait/#async-function-constructor-arguments and following sections.

**Comment by domenic** [comment]
Also https://tc39.github.io/ecmascript-asyncawait/#async-decls-exprs-static-semantics-BoundNames

**Comment by bterlson** [comment]
All of these are fixed with the latest Emu + previous manual fixes. Please open new bugs for any remaining issues!
