### ISSUE TITLE
Fix errors in default parameters

### ISSUE THREAD

**Issue by bterlson** [tc39/proposal-async-await#60]
TC39 wants to see errors thrown from default expressions reject the returned promise rather than throw out. This will likely be an undertaking and require significant refactorings to other areas of the spec. See also #35.

**Comment by zenparsing** [comment]
Looking at [OrdinaryCallEvaluateBody](http://www.ecma-international.org/ecma-262/6.0/#sec-ordinarycallevaluatebody):
- Let status be FunctionDeclarationInstantiation(F, argumentsList).
- ReturnIfAbrupt(status)
- Return the result of EvaluateBody of the parsed code that is the value of F's [[ECMAScriptCode]] internal slot passing F as the argument.

It looks like the only way that _status_ can be an abrupt completion is if
- The arguments object can't be created for some reason (FunctionDeclarationInstantiation step 22), or
- The parameter binding procedure fails (FunctionDeclarationInstantiation step 26).

If both cases should result in rejected promises, then perhaps all we need to do is to change OrdinaryCallEvaluateBody to something like:
- Let status be FunctionDeclarationInstantiation(F, argumentsList).
- If status is an abrupt completion,
  - If the value of the [[FunctionKind]] internal slot of F is "async",
    - _Return a rejected promise with status.[[value]] as the reason (obviously this needs expansion)_
  - Else
    - Return Completion(status).
- Return the result of EvaluateBody of the parsed code that is the value of F's [[ECMAScriptCode]] internal slot passing F as the argument.

**Comment by zenparsing** [comment]
I think we'll need [[FunctionKind]] to be "async", in any case, so that async functions aren't allowed as superclasses in extends clauses and other things like that (14.5.14 g).

**Comment by anba** [comment]
> I think we'll need [[FunctionKind]] to be "async", in any case, so that async functions aren't allowed as superclasses in extends clauses and other things like that (14.5.14 g).

Async functions are no longer constructors, so step 6.f already takes care of the `extends` issue.

**Comment by domenic** [comment]
@zenparsing have you looked at #55, re: [[FunctionKind]]?

**Comment by zenparsing** [comment]
@anba Ah, yes, you're absolutely right.

@domenic Yeah, and I agree that the "function kind-ish-ness" treatment in the spec should be simplified if possible.

**Comment by bterlson** [comment]
I'm having a hard time figuring out when exactly arguments object creation would fail. It seems to be if the creation of caller, callee, length, or @@iterator properties fails but I don't see how it's possible those would fail. I wonder what @allenwb thinks about this situation.

Assuming it can't fail then I think the proposed fix above is fine although I was thinking we could also move FunctionDeclarationInstantiation to inside EvaluateBody. Existing EvaluateBodys would add a call to FDI at step 1 while async functions would put the call at step 3.a of [AsyncFunctionStart](http://tc39.github.io/ecmascript-asyncawait#abstract-ops-async-function-start). This has the advantage of forcing all function body things to pick the time at which they EvaluateBody and prevents complex logic in OrdinaryCallEvaluateBody if we add other function types that have different behaviors.

**Comment by allenwb** [comment]
@zenparsing 
IteratorBindingInitialization includes the evaluation of arbitrary default parameter initialization expressions,so step 26 can be any possible abrupt completion.

@bterlson 
Defining an arguments object (of either kind) can't throw, as far as I can tell, so FDI step 22.c is likely unnecessary. It's probably a left-over from a time where throwing during arguments object creation was a possibility.
You can probably get away with moving the call to FunctionDeclarationInstantiation into the various EvaluateBody actions.  Of course, you will need to add an argumentsList parameter to EvaluateBody.

But the easiest thing might be to just  define a custom [[Call]] for async functions.  All it would need to do (for this purpose, at least) is wrap a call to the Ordinary [[Call]] with a check for an abrupt completion and if necessary returning a rejected promise.

**Comment by bterlson** [comment]
It seems neater to me to handle all promise-creating-and-returning stuff once which is why I like the EvaluateBody solution. Seems to keep things local and easier to understand for me. But now we have three options and I'll just pick the best one once I implement this ;)

**Comment by bterlson** [comment]
FYI: Went with the approach to update the various EvaluateBody runtime semantics to handle FunctionDeclarationInstantiation. Pretty clean, actually.

**Comment by zenparsing** [comment]
I agree, it looks pretty good.
