### ISSUE TITLE
await* [asyncOp(), asyncOp()] -> await Promise.all([asyncOp(), asyncOp()]) ?

### ISSUE THREAD

**Issue by timjacobi** [tc39/proposal-async-await#61]
I'm just wondering why it is not included in the proposal. It is already implemented in Babel.

**Comment by bterlson** [comment]
It doesn't seem useful to me. If it did something similar to yield\* where it saves you from having to write complex loops to get an array of promises I would be OK with it but we just don't need sugar for typing `Promise.all` IMO.

**Comment by zloirock** [comment]
My point - `await* -> Promise.all` very useful and should be returned to the current proposal. Yes, it's only sugar for `Promise.all`, but this proposal completely sugar for generators and promises.

**Comment by domenic** [comment]
And it definitely wouldn't use `*` because it has no correlation with what `*` means for generators.

Babel is just not implementing the spec here.

**Comment by bterlson** [comment]
FWIW, there is no reason await \* can't stand on its own. There is committee consensus behind this proposal without await \* so at this point if people want await \* they can champion it as part of a separate proposal.

**Comment by arv** [comment]
Another point to not do await\* now is that we might want to save it for something better.

**Comment by timjacobi** [comment]
As @domenic  said:

> Babel is just not implementing the spec here.

That's all I wanted to know. Thanks! :)

**Comment by trusktr** [comment]
Is there anything besides `Promise.all()` and `Promise.race()` that people might want to use `async*` for? If not, then this idea:

``` js
await [one, two, three] // async Promise.all([one, two, three])
await* [one, two, three] // async Promise.race([one, two, three])
```

**Comment by ljharb** [comment]
@trusktr it'd be `await` not `async`, but `await [one, two, three]` is a promise for an array of three things.

There's virtually no value in providing a syntax shortcut for `Promise.all` and `Promise.race` - just type them out.
