### ISSUE TITLE
Missing return statements in informative desugaring?

### ISSUE THREAD

**Issue by littledan** [tc39/proposal-async-await#62]
In http://tc39.github.io/ecmascript-asyncawait/#desugaring , I wonder if you want to write 'return' before the last 'step' call and the Promise.resolve call.

**Comment by bterlson** [comment]
Really need to get line numbers in the source listings. But I don't think a return is needed because the return value of the constructor function isn't used for anything afaik? As long as step ultimately calls resolve or reject it should be ok?

**Comment by littledan** [comment]
Oh of course, my mistake

**Comment by bterlson** [comment]
Where is the flogging emoji when you need it???
