### ISSUE TITLE
Suggestion: `await`ing functions

### ISSUE THREAD

**Issue by omidkrad** [tc39/proposal-async-await#64]
`await` waits for a Promise and returns the result. So awaiting something that is not a Promise should produce error. For example: `var a = await 12` doesn't make much sense. I think awaiting a plain function or arrow function is the same, unless the function is treated as a Promise. That is:

``` javascript
async function w() {
    await resolve => setTimeout(resolve, 0);
}
```

IMO should behave the same as

``` javascript
function w() {
    return new Promise(resolve => setTimeout(resolve, 0));
}
```

this will allow to completely abstract use of Promise through async/await. If you want to actually return a function, you would use the `return` keyword instead.

**Comment by getify** [comment]
-1. that seems suuuuuuuper confusing/magical to me, to promote any function that's `await`d to be an implicit constructor function to `Promise(..)`. can't even imagine what kind of error messaging could help correct the majority of developers who would frequently trip over that when accidentally passing a function that wasn't able to be used in such a way.

**Comment by zenparsing** [comment]
Implicit conversion to promise via `then` is crazy enough.

**Comment by bterlson** [comment]
This seems very confusing for little benefit (saving you from typing `new Promise(` and `)` near as I can tell). Also the conceptual model of await awaiting Promise.resolve() of whatever you await is easy and teachable - we should preserve it. Interesting suggestion though!

**Comment by omidkrad** [comment]
What does awaiting an arrow function do? Why isn't it an error?

**Comment by bterlson** [comment]
It currently does the same thing as `await Promise.resolve(() => {})` - it wraps the function in a promise then awaits the result.

**Comment by omidkrad** [comment]
That is exactly what I was trying to suggest. I didn't know it was in the specs already.

**Comment by bterlson** [comment]
Note that what you say in your OP is not what this is doing. Eg. `Promise(()=>{})` is different than `Promise.resolve(() => {})`

**Comment by omidkrad** [comment]
I know that now! Thanks :+1:
