### ISSUE TITLE
Inheritance relationship between AsyncFunction and GeneratorFunction?

### ISSUE THREAD

**Issue by benjamn** [tc39/proposal-async-await#66]
There have been multiple proposals to define semantics for `async` generator functions, the most promising of which is that they should return `AsyncIterator` objects: https://github.com/zenparsing/async-iteration/

Generator function objects are already `instanceof GeneratorFunction`, and it seems like this draft specification is proposing that `async` functions should similarly be `instanceof AsyncFunction`: http://tc39.github.io/ecmascript-asyncawait/#async-function-objects

I worry that introducing this `AsyncFunction` constructor is hostile to the future of `async` generator functions, since a single function object cannot be both `instanceof GeneratorFunction` and `instanceof AsyncFunction`, unless one of `AsyncFunction` or `GeneratorFunction` is in the inheritance chain of the other, since prototypal inheritance in JavaScript does not allow multiple inheritance.

Furthermore, I thought there was a general agreement on the wisdom of not making it easy to distinguish between `async` functions and functions that just happen to return a `Promise`, so I'm wary of introducing a constructor like `AsyncFunction` that invites `instanceof` checks.

Now, since an `async` generator function returns neither a `Generator` object nor a `Promise`, but something different (an `AsyncIterator`), I could imagine that `async` generator functions would be neither `instanceof AsyncIterator` nor `instanceof GeneratorFunction`. Perhaps a new constructor would need to be introduced, called something like `AsyncGeneratorFunction`?

**Comment by domenic** [comment]
Your last paragraph makes the most sense to me. Assuming that async generator functions would have some inheritance relationship with async functions or generator functions seems wrong. They are not LSP-substitutable.

**Comment by benjamn** [comment]
I could live with that. Still a little worried about the difference between `AsyncFunction`s and `Function`s that return a `Promise`, but I guess we already have the `GeneratorFunction` constructor.

**Comment by bterlson** [comment]
It seems unlikely that there will be much value in having a shared prototype will be valuable because it seems unlikely that methods for generators and async functions will "just work" for async generators. So I agree with your last paragraph that async generators should have their own constructor.

Can you clarify the risk of being able to detect async functions? Even if we decided that async functions don't have an instanceOf check, you could detect them by seeing if you can new them (since async functions don't have a construct slot).

**Comment by benjamingr** [comment]
> It seems unlikely that there will be much value in having a shared prototype will be valuable because it seems unlikely that methods for generators and async functions will "just work" for async generators. So I agree with your last paragraph that async generators should have their own constructor.

That, things that make sense on the prototype of generators and async functions shouldn't really be shared here. Things like `map` would behave differently anyway.

**Comment by bterlson** [comment]
I think I can close this as I don't see much support for the notion of a shared prototype between async functions and async generators. But please re-open to discuss more!
