### ISSUE TITLE
Code with error handling is still bloated 

### ISSUE THREAD

**Issue by mohsen1** [tc39/proposal-async-await#71]
Disclaimer: I haven't read the spec fully. I might be wrong about how you _should_ handle errors with async/await. Sorry if it's just noise.

First time I saw `async` functions proposal I got really excited and I thought it will make asynchronous code much cleaner. But now that I'm using it I have the impression that it's almost same amount of code but with different keywords and syntax.

Consider this example using the Fetch API:

``` js
fetch('file.json')
  .then(response => {
    response.json()
    .then(result => {
      console.log('result: ', result);
    })
  })
```

This can be done with `async/await` much cleaner:

``` js
(async ()=> {
  console.log('result: ', await (await fetch('file.json')).json());
})();
```

Now, if I decide to handle errors for fetch() and json() calls my code becomes a lot more bloated:

``` js
(async ()=> {
  let response = null;

  try {
    response = await fetch('file.json');
  } catch (fetchError) {
    console.error(fetchError);

    try {
      console.log('result: ', await response.json());
    } catch(jsonParseError) {
      console.error(jsonParseError);
    }
  }
})();
```

That is not really less than old way of doing async (with error handling):

``` js
fetch('file.json')
  .then(response => {
    response.json()
    .then(result => {
      console.log('result: ', result);
    })
    .catch(jsonParseError => {
      console.error(jsonParseErorr);
    })
  })
  .catch(fetchError => {
    console.error(fetchError);
  })
```

In fact I like the the .then()/.catch() better. 

I don't have any proposal for a better syntax but I want to start the conversation about error handling.

**Comment by dsblv** [comment]
Hello @mohsen1 

I'm not really a pro of this things, but I think the coolest part of promises is error bubbling. In your example we can chain function calls together to get something like this:

``` js
fetch('file.json')
    .then(response => response.json())
    .then(result => {
        console.log('result: ', result);
    })
    .catch(err => {
        console.log(err);
    });
```

... And handle all errors in one `.catch()`.

With `async/await` it _is_ possible to handle errors in same manner:

``` js
(async () => {
    try {
        console.log('result: ', await (await fetch('file.json')).json());
    } catch (err) {
        console.log(err.message);
    }
})();
```

Almost exactly how sync errors were managed back in the days. And that, I beleive, was the main goal of this proposal :cat: 

## 

Please correct me if I'm wrong, I'm relatively new to promises and all..

**Comment by getify** [comment]
> my code becomes a lot more bloated... not really less than old way of doing async (with error handling)... I like the the .then()/.catch() better

I think this sentiment is a symptom of prioritizing the wrong things from code. If your goal is to have shorter, more terse code, yes, the promise API can end up being more terse than use of `try..catch`. But I think the priority should actually be more reason-able, understandable code. **Code is communication.**

`try..catch`, for better or worse, is extremely well understood and familiar across many languages. Moreover, synchronous code semantics are much easier for humans to reason about than asynchronous code semantics. The big win of promises+generators, as codified in the `async function` sugar, is that it layers synchronous semantics on top of asynchronous code... aka "the best of both worlds".

Is the `try..catch` code less terse than the Promise chain code? Yes, in many cases. But it also harkens to semantics which are less familiar to a broader range of developers. Synchronous semantics are better, even if they're a little longer to type out.

**Comment by bterlson** [comment]
I think the key point here is that this is concern is orthogonal to async/await. @mohsen1's concerns apply to purely synchronous code as well - in the "bloated" example, calling synchronous APIs without await would exhibit the same problem. Await is about reifying a promise to a completion value that you can handle with the existing synchronous machinery and better exception handling techniques are out of scope for this proposal.

FWIW, a feature like catch guards would make this pattern easier as you could put all the awaits in a single try block and catch each type of exception with its own catch block. There was a proposal along these lines in the past.

**Comment by mohsen1** [comment]
Thanks for the replies. I like the catch blocks syntax, specially that most of error handling for the same type of error is usually the same. 

``` js
try {
  let resp = await fetch('root.json');
  let root = await resp.json();
  resp = await fetch(root.url);
  let child = await root.json();

  console.log(child);
} catch (jsonSyntaxError) {
  console.error('Failed to parse JSON');
} catch (fetchError) {
  console.error('Failed to load a URL');
}
```

But without types how's it possible to have different `catch` blocks for each type of error?  Can you point us to the proposal for that?

**Comment by bterlson** [comment]
It used to live on the wiki which is unfortunately down :( It's not an active proposal in the current process. I don't recall the details but you could imagine doing an instanceof check as a type check.

**Comment by getify** [comment]
I don't know if this matched whatever proposal you're referring to, but FF has had conditional catch clauses for a long time... always enjoyed those:

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/try...catch#Conditional_catch_clauses

I even wrote myself a transpiler awhile back to be able to use those.

**Comment by bterlson** [comment]
Seems pretty nice, though it really only saves you from one level of indentation and two lines...

```
try {
    myroutine(); // may throw three types of exceptions
} catch (e if e instanceof TypeError) {
    // statements to handle TypeError exceptions
} catch (e if e instanceof RangeError) {
    // statements to handle RangeError exceptions
} catch (e if e instanceof EvalError) {
    // statements to handle EvalError exceptions
} catch (e) {
    // statements to handle any unspecified exceptions
    logMyErrors(e); // pass exception object to error handler
}
```

```
try {
    myroutine(); // may throw three types of exceptions
} catch (e) {
    if (e instanceof TypeError) {
        // statements to handle TypeError exceptions
    } else if (e instanceof RangeError) {
        // statements to handle RangeError exceptions
    } else if (e instanceof EvalError) {
        // statements to handle EvalError exceptions
    } else {
        // statements to handle any unspecified exceptions
        logMyErrors(e); // pass exception object to error handler
    }
}
```

**Comment by inikulin** [comment]
@mohsen1 

If you need "error rewriting" you can do something like this: 

``` js
try {
  let resp = await fetch('root.json').catch(() => { throw 'Failed to load a URL' });
  let root = await resp.json().catch(() => { throw  'Failed to parse JSON' });

  resp = await fetch(root.url).catch(() => { throw 'Failed to load a URL' });
  let child = await root.json().catch(() => { throw 'Failed to parse JSON' });

  console.log(child);
} catch (err) {
  console.error(err);
} 
```

Or to avoid code duplication:

``` js
function fetchResource(url) {
    return fetch(url).catch(() => { throw 'Failed to load a URL' });
}

function parseJsonResp(resp) {
     return resp.json().catch(() => { throw 'Failed to parse JSON' });
}

try {
  let resp = await fetchResource('root.json');
  let root = await parseJsonResp(resp);

  resp = await fetchResource(root.url);
  let child = await parseJsonResp(root);

  console.log(child);
} catch (err) {
  console.error(err);
} 
```

**Comment by getify** [comment]
@bterlson that's precisely what my transpiler did. :)

**Note:** you _must_ have an else with a re-throw in there if you're not otherwise going to have an unconditional catch clause. in older browsers, re-throw screwed up the stack, but in newer browsers it's preserved.
