### ISSUE TITLE
`export async function` proposal

### ISSUE THREAD

**Issue by qfox** [tc39/proposal-async-await#74]
ES2015 has no native asynchronous modular system.

Why not to use a mix of `export` and `async function` to resolve modules somewhere inside?

It will allow us to load any module asynchronously without any changes to our apps.

``` js
import fs from 'fs';

export default async function() {
  return await fs.readFile('somefile');
};
// or even
export default new Promise(resolve => resolve(15));
```

/cc @domenic @douglascrockford

**Comment by inikulin** [comment]
``` js
export default async function() {
  return await fs.readFile('somefile');
};
```

This is already a valid syntax for the async function exports.

If I get it right, you can achieve desired behavior by doing the following:

``` js
export default (async function() {
  return await fs.readFile('somefile');
})();
```

**Comment by qfox** [comment]
The main idea to let modular system to resolve promises by self.

The current code can use `Promise.resolve()` to resolve the result of module if it's a promise. It's called asynchronous provide, afair.

Btw, what's the case of exporting async function atm? Can't imagine a single one, even if it's a valid syntax.

**Comment by inikulin** [comment]
> Btw, what's the case of exporting async function atm? Can't imagine a single one, even if it's a valid syntax.

E.g.:

_fetch.js_

``` js
export default async function(url) {
   var data = await request(url);

   return JSON.parse(data);
}
```

_index.js_

``` js
import fetch from './fetch';

fetch('http://example.com').then(data => {
   ...
});
```

**Comment by qfox** [comment]
@inikulin Am I right that you have code like this in your projects? I have a lot of synthetical examples, but have no a single one from the real life.

**Comment by inikulin** [comment]
@zxqfox yep, why not? There is no difference between this and exporting a function that returns Promise.

**Comment by qfox** [comment]
@inikulin Hmm. Sorry, I've missed your point about a function that returns a Promise.

So you suppose to use `export async IIFE` to force resolution of the module on the side of modular system? It's fine for me, actually. If I see it right it's the same as exporting a Promise.

What you think about putting this in standard somehow or discuss about it? Because I don't see why we shouldn't.

**Comment by RangerMauve** [comment]
@zxqfox Are you saying you want the async function to get evaluated and to have the result set as the export?

Also, the `async` keyword would be part of the IFFE, not before it. It acts the same way as the `*` in generators.

**Comment by qfox** [comment]
@RangerMauve Yeah, exactly.

Thanks for correction. `IIAFE` ;-)

**Comment by RangerMauve** [comment]
Yeah, I think that might be much further down the road, and not really in the scope of this proposal. Maybe after async functions come along, it might make sense to propose async module exports as something separate.

**Comment by bterlson** [comment]
Not going to do this. But, I think this is possible with the module loader (which can intelligently decide what to do with exported values).

**Comment by SummerXIAhaha** [comment]
> > Btw, what's the case of exporting async function atm? Can't imagine a single one, even if it's a valid syntax.
> 
> E.g.:
> 
> _fetch.js_
> 
> ```js
> export default async function(url) {
>    var data = await request(url);
> 
>    return JSON.parse(data);
> }
> ```
> 
> _index.js_
> 
> ```js
> import fetch from './fetch';
> 
> fetch('http://example.com').then(data => {
>    ...
> });
> ```


if I need export the data in index.js. how can i get it? please help me. thank you.
