### ISSUE TITLE
Parallel `await` proposal

### ISSUE THREAD

**Issue by qfox** [tc39/proposal-async-await#75]
Atm there is no intuitive mechanism to resolve few promises in parallel.

Why not to use lists and destructuring to do it?

``` js
let [a, b] = await [Promise.resolve(1), Promise.resolve(2)];
// or
let a, b = await Promise.resolve(1), Promise.resolve(2);
```

**Comment by inikulin** [comment]
There was  `await*` but it was removed. Use `Promise.all`:

``` js
let [a, b] = await  Promise.all([Promise.resolve(1), Promise.resolve(2)]);
```

**Comment by qfox** [comment]
Why to use `await` then? I can use `Promise` everywhere ;-) The idea to hide away `Promise` object at all and still have a power of them.

**Comment by inikulin** [comment]
> Why to use await then? I can use Promise everywhere ;-)

It's completely up to you.

**Comment by inikulin** [comment]
But note what you will not be able to get benefits of "sync-alike" `await` syntax then. Imagine awaiting array of Promises in the cycle. It will be definitely better with `await`. 

>  The idea to hide away Promise object at all and still have a power of them.

It will be just unnecessary sugar (that causes cancer of the semi-colons). You can already achieve desired functionality combining `Promise.all` and `await`, which is enough to provide "sync-alike" syntax and keep `async`-related syntax minimal.

**Comment by qfox** [comment]
Just why not to resolve it via async-await mechanism, if `async function () {}` is like sugar for `function(){ return new Promise...}`. I don't think it's unnecessary, unnecessary is a weak argument, imho.

**Comment by inikulin** [comment]
@zxqfox 

>  I don't think it's unnecessary, unnecessary is a weak argument, imho.
> Less is more.

See https://github.com/tc39/ecmascript-asyncawait#awaiting-non-promise.
With your proposal you will get inconsistency:
`await { foo: 1}` -> `Promise.resolve({ foo: 1})`
`await ['foo']` -> `Promise.resolve(['foo'])`
`await [promise]` -> `Promise.all([promise])`

You will have some unobvious complicated runtime semantics. Therefore you will need explicit syntax sugar for `await all`, that as I described before is redundant since we have `Promise.all`

**Comment by zloirock** [comment]
> that as I described before is redundant since we have `Promise.all`

Async functions are redundant since we have `Promise` and generators :thumbsup:

**Comment by qfox** [comment]
Yeah, I got your point. Can't agree that it was a good idea now ;-) Thanks for clarifications.

**Comment by inikulin** [comment]
@zloirock It's syllogistic fallacy

**Comment by zloirock** [comment]
@inikulin the fallacy here is only in your approval about redundant sugar for parallel awaiting. It's most frequent operation with promise sets. With `await*[x, y]` was `*` - one additional character, with `await Promise.all([x, y])` - 14.

**Comment by inikulin** [comment]
> With await*[x, y] was \* - one additional character, with await Promise.all([x, y]) - 14.

And a lot of grammar and runtime semantic changes. At first I was upset about `await*` removal too and I extensively used it in my code. But since then I don't feel any discomfort using `Promise.all` and I it seems more explicit than `await*`.

**Comment by zloirock** [comment]
> And a lot of grammar and runtime semantic changes.

Orly? :)

> At first I was upset about `await*` removal too and I extensively used it in my code. But since then I don't feel any discomfort using `Promise.all` and I it seems more explicit than `await*`.

Stockholm syndrome.

**Comment by inikulin** [comment]
@zloirock Ah, whatever

**Comment by tmitchel2** [comment]
This is a shame, the await\* syntax was a really nice improvement on the c# original.
