### ISSUE TITLE
function redundant?

### ISSUE THREAD

**Issue by DanielHerr** [tc39/proposal-async-await#77]
Is it really necessary to have "async function" instead of simply "async"?

**Comment by ljharb** [comment]
I think `async() { }` is valid syntax (it's a function invocation followed by a block), because `async` is a valid variable name.

**Comment by bterlson** [comment]
Yes, function is necessary. `async() { }` is not valid syntax, but `async()\n{ }` is (eg. Allman/GNU styles).
