### ISSUE TITLE
Can [[Reject]], [[Resolve]] throw?

### ISSUE THREAD

**Issue by zenparsing** [tc39/proposal-async-await#79]
In AsyncFunctionAwait, step 4 and 5, we call _promiseCapability_.[[Resolve]] and then RIA on the result.  But since we get the promise capability from the intrinsic %Promise%, it seems like it can't throw.

I guess maybe that if someone creates a new realm with new intrinsics, it could throw?

**Comment by anba** [comment]
Yes, the ReturnIfAbrupt calls can be removed or rather replaced with assertions that no abrupt completions are possible. Actually we talked about this the other day on #jslang, where I confessed I added some ReturnIfAbrupts to avoid specifying that abrupt completions are not possible. For example the ReturnIfAbrupt after AsyncFunctionStart in EvaluteBody is not necessary, but it probably requires a sentence or two why abrupt completions cannot happen at this step.
