### ISSUE TITLE
Catching specific exceptions in try-catch vs Bluebird .catch

### ISSUE THREAD

**Issue by Rush** [tc39/proposal-async-await#87]
I am not sure what's the place to discuss this but my gut feeling is that for `async` / `await` to really be a compelling alternative to raw Promises error handling needs to be vastly improved. Bluebird allows you to catch exceptions via:
- `someStuff.catch(CustomErrorClass, err => {/* custom handler */}`
- `fs.unlinkAsync(filename).catch({code: 'ENOENT'}, err => {/* custom handler */}`

And if you're not catching specific exceptions then you're doing it wrong cause your `.catch` or `try { } catch() {}` will catch even `SyntaxError`. You want to catch only the exceptions you're expecting to catch.

I don't want to write:

```
try {
} catch(err) {
  if(err instanceof CustomErrorClass) {
    // handler code
  }
  throw err;
}
```

I have actually looked at my code base and it seems very little functions would actually benefit from async / await cause where I'll be gaining on simplifying the async flow, all the error handling will be blowing out my functions out of proportion.

Consider a function written with bluebird promises:

``` js
function downloadImage(mirrors, fileName, outputFile) {
   return checkFile().then(logOk).catch({code: 'ENOENT'}, err => {
     return fs.unlinkAsync(destFile).catch({code: 'ENOENT'}, () => {})
       .then(() => downloadUrl(mirrors, workDir, fileName))
       .then(() => {
         if (outputFile.match(/\.gz$/)) {
           return runCommand('gunzip', [workFile + '.gz']);
         }
       }).then(() => symlinkAsync(workFile, destFile))
       .then(checkFile)
       .then(logOk);
   });
 }
```

and the one with async / await::

``` js
 async function downloadImage(mirrors, fileName, outputFile) {
   try {
     await checkFile();
     logOk();
   } catch(err) {
     if(err.code === 'ENOENT') {
       try {
         await fs.unlinkAsync(destFile);
       } catch(err) {
         if(err.code !== 'ENOENT') { throw err; }
         await downloadUrl(mirrors, workDir, fileName);
         if (outputFile.match(/\.gz$/)) {
           await runCommand('gunzip', [workFile + '.gz']);
         }
         await symlinkAsync(workFile, destFile);
         await checkFile();
         logOk();
       }
     }
     throw err;
   }
 }
```

My proposal would be to extend capabilities of `try { } catch() {}` to allow whatever bluebird `.catch` support so for example:

``` js
try { 
  fs.unlinkAsync(filename);
  randomFunction();
} catch({code: 'ENOENT'} : err) {
  console.log('File did not exist');
} catch(SyntaxError: err) {
  console.log('Got syntax error');
}
```

Mozilla does support something similar but with less declarative approach. https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/try...catch I'd rather just have it like bluebird has.

Let me know your thoughts.

**Comment by ljharb** [comment]
`Promise`s (and thus, `async` functions) mirror `try/catch`. In order to use catch guards (as Bluebird has), they'd have to be added in `Promise`s, `async` functions, _and_ as a syntactic `try/catch` third option.

At that time, they'd automatically work in `async` functions. Until that time, you'd handle this in `async` functions the same way you would in a `.catch` function or a `catch` block: with an `if` statement that checks the condition you want to check, and rethrows otherwise.

**Comment by Rush** [comment]
Thanks for your reply. I am totally aware of what you said. My primary point is that `try {} catch {}` in ES should mirror what Bluebird does, and so should standard `Promise`s. I have not found any discussion about this and this repo looked like a good place.

**Comment by zenparsing** [comment]
Es-discuss is a good place for language ideas and proposals. This topic has been discussed several times; searching the archives might be helpful.

**Comment by bterlson** [comment]
Appreciate the time you took to lay this out :) But yes, es-disuss is the correct place for this discussion. Catch guards are a common request and something I and others are looking in to (eg. see [this gist](https://gist.github.com/bterlson/da8f02b95b484cd4f8d9)). Improvements to the promise API can also be proposed over there.
