### ISSUE TITLE
AsyncMethod should have static semantics related to SpecialMethod (14.3.7)

### ISSUE THREAD

**Issue by caitp** [tc39/proposal-async-await#91]
For consistency with https://tc39.github.io/ecma262/#sec-static-semantics-specialmethod, and because in current and future implementations, async methods desugar to generators, "constructor" and "prototype" should be illegal property names for AsyncMethods.

**Comment by zenparsing** [comment]
Good catch.  We'll need to add `AsyncMethod` to that SpecialMethod thing.  The name "prototype" is already taken care of by https://tc39.github.io/ecma262/#sec-class-definitions-static-semantics-early-errors, I think.

**Comment by ljharb** [comment]
This proposal is stage 4, and has been merged into the spec as of ES2017.
