### ISSUE TITLE
Returning a rejection does not propagate exception into function body

### ISSUE THREAD

**Issue by zenparsing** [tc39/proposal-async-await#92]
I'm not really proposing any change here, but I wanted to highlight this behavior since I was quite surprised to have not considered it previously.

Consider the following code:

``` js
async function a() {
    throw new Error("can i haz err");
}

async function b() {
    try {
        return a();
    } catch (error) {
        console.log("i haz err in b");
    }
}

b().then(
    _=> { console.log("ok") },
    _=> { console.log("broken") });
```

In this example, `b` will return a rejected promise, but the catch clause in `b` will not get fired.  This pretty much just falls out of the design, but I am wondering if there is a potential here for confusion if users think that they can simply elide the `await` when returning a promise and get the same exact control flow behavior.

(I came across this while wrestling with the promise unwrapping semantics for async generators.)

Thoughts?

@erights
@domenic

**Comment by domenic** [comment]
Hmm, this is not really surprising to me. (To be clear: `broken` will appear, but `i haz err in b` will not.)

Maaaybe you could make the argument that in async functions `return x` should be changed to mean `return await x`, but given how similar discussions went for `yield` in async generator functions I doubt that'll get support.

**Comment by erights** [comment]
Yeah, that implicit await would be a cure worse than the disease, for the same reason. Regarding the surprise, say that a() returned an unresolved promise that, much later, rejects. Wouldn't it be more surprising for b() to stall at the return statement despite the absence of an "await"?

**Comment by zenparsing** [comment]
> implicit await would be a cure worse than the disease

Agreed!

**Comment by RangerMauve** [comment]
@zenparsing If this is the case, then does that suggest that `yield` shouldn't automagically unwrap with regards to https://github.com/tc39/proposal-async-iteration/issues/15 ?

**Comment by zenparsing** [comment]
@RangerMauve It certainly means that implicit `await` before `yield` is not what we want. There is another option for value unwrapping on the producer side though, which @erights mentioned to me recently: we could unwrap the value, not from within the generator function body itself, but from within the "next" method. I'm not sure if that's the right approach yet, though; there are tradeoffs.

**Comment by bterlson** [comment]
I recall discussing implicit await-on-return some years back. fwiw, but this was probably a side conversation... I tend to agree that implicit await is not a good idea and that while the OP code is suspicious, it's not surprising and can be explained without much difficulty.

>  Regarding the surprise, say that a() returned an unresolved promise that, much later, rejects. Wouldn't it be more surprising for b() to stall at the return statement despite the absence of an "await"?

How would this stalling be observable to a programmer, though?

**Comment by zenparsing** [comment]
> How would this stalling be observable to a programmer, though?

It would be observable if there were a finally block.  The finally block will either run immediately or after the to-be-returned promise resolves, depending on the implicit `await` choice.

**Comment by zenparsing** [comment]
Closing this, thanks for discussing!
