### ISSUE TITLE
Debugging async/await

### ISSUE THREAD

**Issue by codepunkt** [tc39/proposal-async-await#93]
I'm having spotty debugging experiences when I try to debug code with async/await using transform-async-to-generator babel plugin.

@amcdnl had the same problems and opened an issue at https://github.com/mozilla/source-map/issues/221 which describes the issue in more detail and has some interesting discussion about debugging async/await.

Is the debugging experience part of this proposal? Was this thought about before (e.g. in respect to how other languages having async/await syntax handle debugging)?

**Comment by bterlson** [comment]
This proposal has nothing normative to say about the debugging experience, however debuggability (and, in general, developer experience) is a critical piece of input into the design of any new feature. As far as I am aware there is nothing inherent in the async functions proposal that would make debugging experience poor. If there are such issues, please raise them!

**Comment by codepunkt** [comment]
I don't want to insinuate anything, but did you really read the linked issue and discussion at mozilla/source-map#221?

I think the issue at hand dates from debugging generators and yield statements, which face the same issues.

The debugging flow exits the current frame whenever a `yield` or in this case, `await`, is stepped over. This is not a good experience because, even though any other code could run in between, hitting other breakpoints, the debugging flow should be resumed in the statement after the `await` without having to manually set a breakpoint there.

**Comment by RangerMauve** [comment]
I'm not sure that specs like this have any say on what the debugger implementations in various browsers decide on doing or are capable of doing. This seems more like an issue that should be brought up on the issue trackers of the various browser engines.

**Comment by marcoscaceres** [comment]
Recommendations to dev tool implementors don't hurt: specially for known pain points, such as these. Having said that, I think everyone is aware of how annoying it currently is to debug async/generator code.

**Comment by codepunkt** [comment]
@RangerMauve i beg to differ. i don't think it will help anyone if every browser does its own thing. we've had that in the past and know where this led us. i'd rather have people working together, creating a great experience that includes debugging.

**Comment by RangerMauve** [comment]
@gonsfx I'm not against talking about it or anything, I'm just not sure that there are browser implementers that'd be responsible for that actually paying attention to this. And without them in the conversation I doubt it'd have much effect on anything.

Maybe if someone knows them they could ping a couple into the thread?

**Comment by getify** [comment]
This repo is supposed to be for TC39 discussion. It's admirable to want engines to agree on things like debugging experience -- i've spent enormous amounts of time trying to get other devtools related experiences to be "standardized", mostly without success -- but this stuff is just not in the purview of TC39. That kind of discussion might need to happen, but should be conducted elsewhere.

PS: if you want to argue that it should be TC39's purview to standardize such things, this repo/thread is _also_ not the right place to do so. That kind of discussion should go on es-discuss.

**Comment by inikulin** [comment]
@gonsfx 

> The debugging flow exits the current frame whenever a yield or in this case, await, is stepped over. This is not a good experience because, even though any other code could run in between, hitting other breakpoints, the debugging flow should be resumed in the statement after the await without having to manually set a breakpoint there.

I'm just curious how do you imagine it should work?

**Comment by inikulin** [comment]
@gonsfx 
Let's use the following code:

``` js
func1() {
 doSomething(); // I have breakpoint here
}

async func2() {
    await something(); // I'm stepping here
    doSomethingElse();
}
```

Imagine you hit step over at `await` in `func2`. While operation in `func2` is awaited `func1` gets executed. How debbuger should behave? Ignore breakpoint in `func1`? I don't think it's a good debugging experience. Somehow postpone execution of code in `func1()`? This may cause side effects, making program non-deterministic. 
You can argue that we can enable stepping over if no other breakpoints are set. But it's not predictable behavior, also how should debugger behave in this case?:

``` js
async func() {
    await neverResolved(); // Stepping here
}
```

**Comment by codepunkt** [comment]
@getify I don't know whats in the purview of TC39 and what is not. Thanks for your clarification on that matter. Nevertheless, the TC39 website reads

> Standardization of the general purpose, cross platform, vendor-neutral programming language ECMAScript. This includes the language syntax, semantics, and libraries and complementary technologies that support the language.

To me, the debuggability of a language is one of its integral parts and should play a major part in all efforts to improve the language. Even though you can argue about my stance on this, "_complementary technologies that support that language_" is a broad formulation.

I'm quite sure devtools and debugging are considered by TC39 - see `HostPromiseRejectionTracker` for an example.

@inikulin Thats exactly the kind of discussion that i hoped would develop.

In your example, the breakpoint in `func1` should not be ignored. If you resume after the breakpoint in `func1` was hit, the debugger could simply ignore you previously stepping over the `await` in `func2`. I'm not sure i like that, though. I would rather have it continue there once the `await` has been resolved by means of a new temporary breakpoint that was set by the development tools at `doSomethingElse` the moment you stepped over the `await` one line above.

In your second example, there would also be a temporary breakpoint set by the debugger when you stepped over the `await`, but that breakpoint would never be hit as the `await` never resolves.

**Comment by getify** [comment]
@gonsfx as I already said, discussion of what JS should or should not do, or what the spec should or should not say, **does not belong here**. The issue tracker on TC39's github is not a general discussion or proposal area. It's intended purpose is to track issues with the already written spec and track concrete proposals from strawman through to finished status.

The es-discuss list is where you debate this kind of stuff. Please take the conversation there.

**Comment by inikulin** [comment]
> The issue tracker on TC39's github is not a general discussion or proposal area. It's intended purpose is to track issues with the already written spec and track concrete proposals from strawman through to finished status.
> 
> The es-discuss list is where you debate this kind of stuff. Please take the conversation there.

If so, I guess it should be written in the README and CONTRIBUTION.md. Because otherwise you can't blame people for the desire to discuss `async/await` spec in `async/await` spec repo on GitHub.

**Comment by marcoscaceres** [comment]
> On 13 Apr 2016, at 10:36 PM, Kyle Simpson notifications@github.com wrote:
> 
> @gonsfx as I already said, discussion of what JS should or should not do, or what the spec should or should not say, does not belong here. The issue tracker on TC39's github is not a general discussion or proposal area. It's intended purpose is to track issues with the already written spec and track concrete proposals from strawman through to finished status.
> 
> The es-discuss list is where you debate this kind of stuff. Please take the conversation there.

It is deeply saddening to hear you telling people to go back mailing lists. We (the standards community) moved to GitHub **precisely** so we could have these discussions here on GitHub: it was to bring standards and developers together to the same forum to foster new forms of participation and inclusion. 

This is the right place to have these discussions. Mailing lists should only be used for administrative announcements.

**Comment by bterlson** [comment]
@gonsfx for the record, yes I read the linked thread, and no I still don't believe there is anything normative we want to say here. Tooling experience is something we let browsers iterate and innovate on. Proposing that TC39 provide normative language for tooling experiences would have to be advanced in the context of 262, not a particular proposal.

> It is deeply saddening to hear you telling people to go back mailing lists. We (the standards community) moved to GitHub **precisely** so we could have these discussions here on GitHub

This is a fair concern. We have decided to use the ecma262 repository for "known" 262 issues, and not for new feature ideas. This is primarily to keep it focused, and seems ok since es-discuss has a long history of usage for feature requests and such. We could investigate moving es-discuss to another tc39 GitHub repo if it would be of help to you, although I'm skeptical that GitHub issues are the best approach for discussion like this. Probably starting a thread on es-discuss is the right first step.

**Comment by marcoscaceres** [comment]
@bterlson, I know this is not the WHATWG, I'd encourage you to consider:
https://blog.whatwg.org/github

And also, the 5th paragraph from @domenic's post on streams (which may become ES language feature): https://blog.whatwg.org/streams

**Comment by towerofnix** [comment]
> bterlson, I know this is not the WHATWG, I'd encourage you to consider:
> https://blog.whatwg.org/github
> 
> And also, the 5th paragraph from domenic's post on streams (which may become ES language > feature): https://blog.whatwg.org/streams

A bit off-topic.. but, when I go to these links, I get this error:

![screenshot](https://cloud.githubusercontent.com/assets/9948030/14636453/f8f5c2be-0601-11e6-82c4-10c8c09d77d5.png)

I suppose it just means I'm not allowed to view the blog ("access denied for user whatbloguser") but I'm not sure if this is intentional or if maybe that page should be updated?

Poor me, not being in the list of leet hax0rs who have access to the blog.. 😛

(PS, the main site https://whatwg.org/ works.)

(PPS, Not sure where I should ask about this?)

**Comment by domenic** [comment]
We are having server problems at the moment :(. You can use archive.org in the meantime.

**Comment by amcdnl** [comment]
Whats the status on this?

**Comment by bterlson** [comment]
Status on what? There seem to be a number of issues raised in this thread.

**Comment by amcdnl** [comment]
@bterlson -  There is a lot of off-topic chat and no one taking action. I'm asking is TC39 going to take responsibility and if not who should we start collaborating with them on a fix?

**Comment by bterlson** [comment]
A fix for dev tools not having good async debugging capabilities? I'd start by filing bugs on the dev tools teams you want to improve their debugging experience.
