### ISSUE TITLE
Qs about Informative Desugaring

### ISSUE THREAD

**Issue by rossberg** [tc39/proposal-async-await#94]
Two questions:
- The text claims that the `<body>` of the async function is simply used as the body of a generator. However, that does not explain what happens to `await`, which would need to be transformed into yields. Is there anything non-trivial about that that would not make it straightforward to describe as a desugaring as well?
- How can the reject handler in lines 41/42 of the `step` function ever be reached?

**Comment by zenparsing** [comment]
- In the desugaring, awaits just become yields. The `Promise.resolve` magic happens in the generator wrapper.
- The reject handler will get call if the await operator evaluates to a promise that is (eventually) rejected.

``` js
async function f() {
  let error  = new Error();
  try {
    await Promise.reject(error);
  } catch (x) {
    assert(x === error);
  }
}
```

**Comment by domenic** [comment]
> Is there anything non-trivial about that that would not make it straightforward to describe as a desugaring as well?

I believe the precedence rules for yield are different from await. e.g. `await 1 + 2` vs. `yield 1 + 2`.

**Comment by rossberg** [comment]
@zenparsing, ah, thanks! I suppose I keep getting confused about all the different places where recursive unwrapping magic interferes and can cause failure, such as in `resolve`.

@domenic, can't that be handled trivially by having the desugaring insert parens? I mean, desugarings are usually understood to apply to the AST anyway, not the raw text.

**Comment by domenic** [comment]
Sure, just wasn't sure what you considered trivial, since you weren't clear on the await to yield substitution.

**Comment by ljharb** [comment]
This proposal is stage 4, and has been merged into the spec as of ES2017.
