### ISSUE TITLE
NOTE 1 for Async Function Definitions says different things than rules

### ISSUE THREAD

**Issue by arai-a** [tc39/proposal-async-await#96]
https://tc39.github.io/ecmascript-asyncawait/#async-function-definitions

> NOTE 1
> `yield` is _Identifier_ or _YieldExpression_ in _FunctionParameters_ of _AsyncFunctionDeclaration_ and _AsyncFunctionExpression_ and _ArrowParameters_ of _AsyncArrowFunction_ depending on context.
- _FunctionParameters_ rule doesn't exist
- `yield` is always _Identifier_ in _FormalParameters_ of _AsyncFunctionDeclaration_ and _AsyncFunctionExpression_

I guess, the note was about _BindingIdentifier_ and _AsyncArrowBindingIdentifier_ ?

**Comment by ljharb** [comment]
This proposal is stage 4, and has been merged into the spec as of ES2017.
