### ISSUE TITLE
Update of "State of this proposal" pharagraph in https://tc39.github.io/ecmascript-asyncawait/

### ISSUE THREAD

**Issue by q2dg** [tc39/proposal-async-await#97]
The current text is "This proposal was accepted into Stage 3 ("Candidate") of the ECMAScript spec process in September 2015. The champion intends for this proposal to be accepted into Stage 4 ("Finished") by the end of November."

Now November has gone time ago...are some new news about this?
Thanks!

**Comment by bterlson** [comment]
Waiting for the second browser implementation as some on the committee feel we need this before advancing this proposal. I will update the text!

**Comment by DanielHerr** [comment]
Both Chrome and Firefox are implementing.

https://bugs.chromium.org/p/v8/issues/detail?id=4483
https://bugzilla.mozilla.org/show_bug.cgi?id=1185106

**Comment by chicoxyzzy** [comment]
Safari too
https://bugs.webkit.org/show_bug.cgi?id=156147

**Comment by IanVS** [comment]
It looks like it moved to stage 4, so I guess the document should be updated? (https://github.com/tc39/proposals/commit/e8c03544751b071b973064ef7d437a34ac6752cd)

**Comment by bterlson** [comment]
Indeed it should be :) I am working on doing the official 262 PR this week and retiring this repo so it should be a non issue soon!

**Comment by littledan** [comment]
Since it's taking some time to get the PR in (understandably, it's huge), would it make sense to update the doc to say it's at Stage 4? This caused some confusion on my team.

**Comment by bterlson** [comment]
Will do so on Tuesday once I return to work. Although I'm kind of hoping I can get the whole PR done with another day's effort :)

**Comment by bterlson** [comment]
Actually I just went ahead and did it (forgot I could use the web interface).
