### ISSUE TITLE
Exceptions swallowed by design?

### ISSUE THREAD

**Issue by mstade** [tc39/proposal-async-await#99]
I've been playing around with async/await thanks to babel recently, and was surprised (although I suppose I shouldn't have been) at how difficult this was to use. Not in terms of syntax, it's quite convenient, but because errors are swallowed and it's incredibly easy to end up in this trap:

``` javascript
async function foo() {
  let bar = await thisWillFail()
  return 'sad face'
}

// Calling foo will fail, but we won't know
let thing = foo()
```

This is obviously over simplified, but I find myself in this situation all the time. To the point where now, I wrap everything in try/catch clauses and `console.log` errors just to see why my application fails in unexpected ways, and often has no useful feedback to give as to why.

I understand _why_ this is; or at least, I think I do. (I'm not that well versed in spec lingo.) I read the spec and it seems this syntax sugar just delegates to promises to deal with all of the mechanics, and promises swallow errors like there's no tomorrow. While I find promises swallowing errors confusing as well, I think it's a bit more forgivable since the syntax is so explicit – there's no sugar to hide away the complexities.

**So for the million dollar question:** is swallowing errors an intentional "feature" by design, or is it possible and meaningful to add language that says implementations must deal with _unhandled_ errors in much the same way you'd be used to seeing them in synchronous operations?

I'd understand if this is difficult to do in an efficient manner, while still preserving stack traces and what not, but perhaps there's a compromise in there somewhere to at least let developers know that just because everything _seems_ to be running without errors, it isn't necessarily so? Also, if I've misread the spec, and this is just a problem with the compiled code, I'd be very happy to stand corrected!

**Comment by ljharb** [comment]
Swallowing errors is how Promises work, by design. You need to add a `.catch()` handler to `thing` if you want to observe any errors/rejections it may have had. The same "problem"/requirement would exist with any function that returns a Promise. Because the rejection happens on a future tick, it would be _impossible_ to synchronously determine if `thing` is rejected at the moment that `foo` returns.

There exist hooks in the spec for implementations to, for example, console.warn on unhandled rejections, and then later remove the console warning if the rejection becomes handled - which I believe Chrome does already. This isn't something the language itself can define, however.

**Comment by mstade** [comment]
I understand that promises are designed to work like this, but it doesn't make it any less confusing; and with this syntactic sugar it becomes much easier to fall into this trap, exacerbating the issue.

In the above case, `thisWillFail()` because it doesn't exist, and `foo` _would_ throw before returning, in the same tick. But whether the error occurs in the same tick or a future tick is beside the point – it's still confusing, annoying, and not least costly to perform the debugging dance to try and figure out _where_ things failed (why is easier, once you know the where.) I understand your point though, making any change to this behavior would mean fundamentally changing how unhandled promise rejections work. While a shame in my opinion, I presume that'd be way out of scope for this spec.

Thanks for the comments @ljharb. I'm keen to learn more about the hook you mention, where can I read more about that? (If it's in _this_ spec, I've definitely missed it.)

**Comment by ljharb** [comment]
Everything after the first `await` keyword happens on the next tick, but also, even if it was `async function foo() { throw 1 }` the rejection would still be processed on the next tick.

The hooks I'm referring to are [here](https://tc39.github.io/ecma262/#sec-host-promise-rejection-tracker) which are called in a number of places.

**Comment by mstade** [comment]
Thank you very much @ljharb, I learned new things today!
